import type { LearningVideo, PracticeQuestion, RoutineBlock } from "./types";

export const PRACTICE_QUESTIONS: PracticeQuestion[] = [
  {
    id: "ielts-r1",
    exam: "IELTS",
    section: "Reading",
    skill: "Main idea",
    difficulty: "Foundation",
    passage: "Urban community gardens often begin on unused land. Besides producing food, they can reduce summer heat, create habitats for insects, and give neighbours a shared project. Their success, however, depends on reliable access to water and long-term permission to use the land.",
    prompt: "What is the main purpose of the passage?",
    options: [
      "To argue that all unused land should become farmland",
      "To describe benefits and practical needs of community gardens",
      "To explain why insects damage city gardens",
      "To compare rural and urban food prices",
    ],
    answer: 1,
    explanation: "The passage presents several benefits and then names two conditions needed for success.",
  },
  {
    id: "ielts-r2",
    exam: "IELTS",
    section: "Reading",
    skill: "Inference",
    difficulty: "Medium",
    passage: "A university library extended its closing time by two hours during exams. Attendance increased sharply after 9 p.m., but electricity use rose only slightly because most lighting systems already operated until the original closing time.",
    prompt: "Which statement is supported by the passage?",
    options: [
      "The library became less popular during exams",
      "Most students arrived before 9 p.m.",
      "The longer opening time added limited energy cost",
      "The university replaced all of its lights",
    ],
    answer: 2,
    explanation: "Attendance rose while electricity use increased only slightly, so the extension had a limited extra energy cost.",
  },
  {
    id: "ielts-l1",
    exam: "IELTS",
    section: "Listening",
    skill: "Detail tracking",
    difficulty: "Foundation",
    passage: "Transcript: The study-skills workshop has moved from Room 204 to the ground-floor seminar hall. It still begins at 3:30 p.m., but students should arrive ten minutes early to collect the workbook.",
    prompt: "Where will the workshop take place?",
    options: ["Room 204", "The library", "The seminar hall", "The admissions office"],
    answer: 2,
    explanation: "The speaker says the workshop moved to the ground-floor seminar hall.",
  },
  {
    id: "ielts-w1",
    exam: "IELTS",
    section: "Writing",
    skill: "Coherence",
    difficulty: "Advanced",
    prompt: "Which sentence best introduces a balanced discussion about remote learning?",
    options: [
      "Remote learning is obviously perfect for everybody.",
      "Technology is everywhere and people use computers.",
      "Although remote learning increases flexibility, its effect depends on access, course design, and student support.",
      "This essay will talk about many things related to education.",
    ],
    answer: 2,
    explanation: "The sentence establishes a clear position while signalling multiple factors for a balanced discussion.",
  },
  {
    id: "ielts-s1",
    exam: "IELTS",
    section: "Speaking",
    skill: "Development",
    difficulty: "Medium",
    prompt: "Which answer best develops the question: “Do you prefer studying alone or with others?”",
    options: [
      "Alone.",
      "I prefer studying alone because I can control the pace. For difficult topics, however, I schedule a short group session to compare solutions.",
      "Studying is important for students.",
      "It depends and I do not know.",
    ],
    answer: 1,
    explanation: "It answers directly, gives a reason, and adds a relevant qualification.",
  },
  {
    id: "sat-m1",
    exam: "SAT",
    section: "Math",
    skill: "Linear equations",
    difficulty: "Foundation",
    prompt: "A tutoring centre charges a fixed registration fee of $12 and $8 per session. Which expression gives the total cost, in dollars, for n sessions?",
    options: ["12n + 8", "8n + 12", "20n", "8(n + 12)"],
    answer: 1,
    explanation: "The variable cost is 8n and the one-time fixed fee is 12, so the total is 8n + 12.",
  },
  {
    id: "sat-m2",
    exam: "SAT",
    section: "Math",
    skill: "Percent change",
    difficulty: "Medium",
    prompt: "A practice score increases from 1200 to 1320. What is the percent increase?",
    options: ["9%", "10%", "11%", "12%"],
    answer: 1,
    explanation: "The increase is 120. Dividing 120 by the original 1200 gives 0.10, or 10%.",
  },
  {
    id: "sat-r1",
    exam: "SAT",
    section: "Reading & Writing",
    skill: "Transitions",
    difficulty: "Foundation",
    passage: "The first prototype was inexpensive to build. _____, it failed repeatedly during outdoor testing, so the team redesigned its protective casing.",
    prompt: "Which choice most logically completes the text?",
    options: ["Similarly", "However", "For example", "Therefore"],
    answer: 1,
    explanation: "“However” signals the contrast between low cost and poor outdoor performance.",
  },
  {
    id: "sat-r2",
    exam: "SAT",
    section: "Reading & Writing",
    skill: "Evidence",
    difficulty: "Advanced",
    passage: "Researchers compared two groups learning the same vocabulary. One reviewed all words once; the other reviewed smaller sets over four days. Both groups spent equal total time, but the second group remembered more words one month later.",
    prompt: "Which conclusion is best supported?",
    options: [
      "Longer total study time always improves memory",
      "Vocabulary cannot be learned in one session",
      "Spacing study across days can improve long-term recall",
      "Smaller word lists contain easier words",
    ],
    answer: 2,
    explanation: "Total time was controlled, while spaced review produced better recall one month later.",
  },
  {
    id: "sat-m3",
    exam: "SAT",
    section: "Math",
    skill: "Quadratics",
    difficulty: "Advanced",
    prompt: "For what positive value of k does x² - 10x + k have exactly one real solution?",
    options: ["10", "20", "25", "50"],
    answer: 2,
    explanation: "Exactly one real solution means the discriminant is zero: 100 - 4k = 0, so k = 25.",
  },
];

export const DEFAULT_ROUTINE: RoutineBlock[] = [
  { id: "routine-1", day: "Monday", start: "07:00", end: "08:00", title: "Academic deep work", category: "study" },
  { id: "routine-2", day: "Monday", start: "20:00", end: "20:45", title: "IELTS reading sprint", category: "exam" },
  { id: "routine-3", day: "Tuesday", start: "19:00", end: "20:30", title: "Flagship project", category: "project" },
  { id: "routine-4", day: "Wednesday", start: "21:00", end: "21:30", title: "Scholarship evidence log", category: "application" },
  { id: "routine-5", day: "Thursday", start: "20:00", end: "21:00", title: "SAT Math practice", category: "exam" },
  { id: "routine-6", day: "Friday", start: "17:30", end: "18:15", title: "Weekly review", category: "study" },
  { id: "routine-7", day: "Saturday", start: "09:00", end: "11:00", title: "Timed mock exam", category: "exam" },
  { id: "routine-8", day: "Sunday", start: "18:00", end: "18:45", title: "Plan the next week", category: "wellbeing" },
];

export const LEARNING_VIDEOS: LearningVideo[] = [
  { id: "ielts-listening-topics", title: "IELTS Listening topics and practice", exam: "IELTS", topic: "Listening", source: "TakeIELTS Official", duration: "Guided lesson", youtubeId: "kvF4hR4tvqc", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-listening-test", title: "IELTS Listening practice test with answers", exam: "IELTS", topic: "Listening", source: "Crack IELTS with Rob", duration: "Practice test", youtubeId: "TVvoyCstDr4", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-listening-full", title: "IELTS Listening full exam practice", exam: "IELTS", topic: "Listening", source: "Masum Bin Alam", duration: "Full practice", youtubeId: "Y63kmQrofzo", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-listening-computer", title: "Computer-based IELTS Listening test", exam: "IELTS", topic: "Listening", source: "Knowledge Island", duration: "Practice test", youtubeId: "JJq6gyCudrI", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-reading-improve", title: "IELTS Reading skills and preparation", exam: "IELTS", topic: "Reading", source: "British Council Teacher Trainer", duration: "Guided lesson", youtubeId: "DrATVKQ9yNg", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-reading-types", title: "IELTS Academic Reading question types", exam: "IELTS", topic: "Reading", source: "TakeIELTS Official", duration: "Strategy lesson", youtubeId: "m9x9fZCBIMY", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-reading-tips", title: "British Council IELTS Reading tips", exam: "IELTS", topic: "Reading", source: "British Council Vietnam", duration: "Tips lesson", youtubeId: "FU_StsHcC-0", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-reading-band9", title: "Band 9 IELTS Reading strategy", exam: "IELTS", topic: "Reading", source: "IELTS Advantage", duration: "Strategy lesson", youtubeId: "apOCnYpR-9g", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-writing-overview", title: "Understand IELTS Writing Tasks 1 and 2", exam: "IELTS", topic: "Writing", source: "TakeIELTS Official", duration: "Official overview", youtubeId: "M1ebzRy77jM", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-writing-task1", title: "Improve IELTS Writing Task 1", exam: "IELTS", topic: "Writing", source: "TakeIELTS Official", duration: "Task 1 lesson", youtubeId: "OL2I07bk9WM", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-writing-task2", title: "Master IELTS Writing Task 2 response", exam: "IELTS", topic: "Writing", source: "TakeIELTS Official", duration: "Task 2 lesson", youtubeId: "axYuP7T2uaA", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-writing-opinion", title: "IELTS Writing Task 2 opinion essays", exam: "IELTS", topic: "Writing", source: "TakeIELTS Official", duration: "Essay lesson", youtubeId: "I2Tj8eh7OLM", officialUrl: "https://takeielts.britishcouncil.org/take-ielts/prepare" },
  { id: "ielts-vocabulary", title: "IELTS Speaking vocabulary", exam: "IELTS", topic: "Speaking", source: "British Council Teacher Trainer", duration: "Short lesson", youtubeId: "LQQE2hWrl98", officialUrl: "https://caribbean.britishcouncil.org/exam/ielts/prepare/videos/speaking" },
  { id: "ielts-grammar", title: "IELTS Speaking grammar criteria", exam: "IELTS", topic: "Speaking", source: "TakeIELTS Official", duration: "Short lesson", youtubeId: "Yq6IZBtM4IU", officialUrl: "https://caribbean.britishcouncil.org/exam/ielts/prepare/videos/speaking" },
  { id: "ielts-fluency", title: "IELTS Speaking fluency and coherence", exam: "IELTS", topic: "Speaking", source: "British Council Teacher Trainer", duration: "Short lesson", youtubeId: "2SI0twnNEN8", officialUrl: "https://caribbean.britishcouncil.org/exam/ielts/prepare/videos/speaking" },
  { id: "ielts-pronunciation", title: "IELTS Speaking pronunciation", exam: "IELTS", topic: "Speaking", source: "TakeIELTS Official", duration: "Short lesson", youtubeId: "UawwTSzaZzk", officialUrl: "https://caribbean.britishcouncil.org/exam/ielts/prepare/videos/speaking" },
  { id: "sat-rw-synthesis", title: "SAT rhetorical synthesis worked example", exam: "SAT", topic: "Reading and Writing", source: "Khan Academy SAT", duration: "Worked example", youtubeId: "FJnzYoKM_tk", officialUrl: "https://www.khanacademy.org/test-prep/sat-reading-and-writing" },
  { id: "sat-rw-science1", title: "SAT science reading method, part 1", exam: "SAT", topic: "Reading and Writing", source: "Khan Academy SAT", duration: "Strategy lesson", youtubeId: "EZp4S_8K5Yo", officialUrl: "https://www.khanacademy.org/test-prep/sat-reading-and-writing" },
  { id: "sat-rw-science2", title: "SAT science reading method, part 2", exam: "SAT", topic: "Reading and Writing", source: "Khan Academy SAT", duration: "Strategy lesson", youtubeId: "nMNp6JkPizQ", officialUrl: "https://www.khanacademy.org/test-prep/sat-reading-and-writing" },
  { id: "sat-rw-synthesis-quick", title: "SAT rhetorical synthesis quick example", exam: "SAT", topic: "Reading and Writing", source: "Khan Academy SAT", duration: "Quick example", youtubeId: "r2XfkWXYU44", officialUrl: "https://www.khanacademy.org/test-prep/sat-reading-and-writing" },
  { id: "sat-math-linear-basic", title: "SAT linear equations basic example", exam: "SAT", topic: "Math", source: "Khan Academy SAT", duration: "Worked example", youtubeId: "fmt6mKBQhVg", officialUrl: "https://www.khanacademy.org/test-prep/sat-math" },
  { id: "sat-math-linear-hard", title: "SAT linear equations harder example", exam: "SAT", topic: "Math", source: "Khan Academy SAT", duration: "Worked example", youtubeId: "8gnpIIy-g3c", officialUrl: "https://www.khanacademy.org/test-prep/sat-math" },
  { id: "sat-math-volume-basic", title: "SAT volume word problems basic example", exam: "SAT", topic: "Math", source: "Khan Academy SAT", duration: "Worked example", youtubeId: "q9_L7aTmbZw", officialUrl: "https://www.khanacademy.org/test-prep/sat-math" },
  { id: "sat-math-volume-hard", title: "SAT volume word problems harder example", exam: "SAT", topic: "Math", source: "Khan Academy SAT", duration: "Worked example", youtubeId: "2cS-oBcmwAw", officialUrl: "https://www.khanacademy.org/test-prep/sat-math" },
];
